### PR TITLE
DGAT-355: Switched to tomcat, added tests and fixed JDBC issues. 

### PR DESCRIPTION
**Pull request by nleck**

### CODE REVIEW

**Review by mufaddaltaiyeb — DISMISSED** [review]
Updates fit for purpose.

**Review by jwalterlarson — DISMISSED** [review]

**Review by mufaddaltaiyeb — APPROVED** [review]
Updates fit for purpose.

**Review by mufaddaltaiyeb — APPROVED** [review]
Updates fit for purpose.

**Review by jwalterlarson — APPROVED** [review]
Approve.

**Review by jwalterlarson — APPROVED** [review]
Approve.

**Review by jwalterlarson — APPROVED** [review]
Approve.

**Review by jwalterlarson — DISMISSED** [review]
Approve.

**Review by jwalterlarson — DISMISSED** [review]
Approve.

**Review by jwalterlarson — APPROVED** [review]
Approve.

**Pull request merged**
